apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufology-db
  namespace: ufology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ufology-db
  template:
    metadata:
      labels:
        app: ufology-db
    spec:
      containers:
        - name: postgres
          image: leogloriainfnet/ufodb:1.0-win
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "devops2025!"
            - name: POSTGRES_DB
              value: "ufology"