apiVersion: v1
kind: Service
metadata:
  name: ufology-redis-service
  namespace: ufology
spec:
  selector:
    app: ufology-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP