apiVersion: v1
kind: Service
metadata:
  name: ufology-db-service
  namespace: ufology
spec:
  type: ClusterIP
  selector:
    app: ufology-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432